name: atac-seq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python version
  - python=3.9
  
  # Core packages
  - numpy=1.21
  - pandas=1.3
  - scipy=1.7
  
  # Visualization
  - matplotlib=3.4
  - seaborn=0.11
  - matplotlib-venn=0.11
  - plotly=5.3
  
  # Bioinformatics tools
  - bedtools=2.30
  - samtools=1.13
  - pybedtools=0.9
  - biopython=1.79
  - pysam=0.17
  
  # Machine learning
  - scikit-learn=0.24
  - statsmodels=0.12
  
  # R and R packages
  - r-base=4.1
  - r-tidyverse
  - r-ggplot2
  - r-pheatmap
  - bioconductor-genomicranges
  - bioconductor-chipseeker
  - bioconductor-clusterprofiler
  - bioconductor-deseq2
  - bioconductor-rtracklayer
  
  # Utilities
  - jupyter
  - jupyterlab
  - tqdm
  - click
  - pyyaml
  
  # Development tools
  - ipykernel
  - nb_conda_kernels